export const integrationSummary = [
  {
    label: 'Connected Apps',
    value: '6',
    helper: 'Core tools currently linked',
  },
  {
    label: 'Last Successful Sync',
    value: '2 min ago',
    helper: 'Most recent confirmed update',
  },
  {
    label: 'Active Workflows',
    value: '8',
    helper: 'Bookings, follow-up, and lead routing',
  },
  {
    label: 'Sync Health',
    value: 'Healthy',
    helper: 'All critical connections running',
  },
];

export const integrationSections = [
  {
    title: 'CRM Integrations',
    description: 'Keep leads, call outcomes, and pipeline stages aligned across your sales system.',
    features: [
      'Create new leads',
      'Update contact records',
      'Track call outcomes',
      'Move opportunities into pipeline stages',
    ],
    items: [
      {
        appName: 'GoHighLevel',
        appCode: 'GHL',
        status: 'Connected',
        syncState: 'Healthy',
        lastSync: '4 minutes ago',
        description: 'Push new enquiries into GoHighLevel and keep follow-up activity visible for your team.',
        primaryAction: 'Manage',
        secondaryAction: 'Disconnect',
      },
      {
        appName: 'HubSpot',
        appCode: 'HS',
        status: 'Connected',
        syncState: 'Healthy',
        lastSync: '11 minutes ago',
        description: 'Create contacts, log call outcomes, and keep deal stages updated automatically.',
        primaryAction: 'Manage',
        secondaryAction: 'Disconnect',
      },
      {
        appName: 'Salesforce',
        appCode: 'SF',
        status: 'Not Connected',
        syncState: 'Ready to connect',
        lastSync: 'No sync yet',
        description: 'Sync captured leads and opportunity updates into your Salesforce workflow.',
        primaryAction: 'Connect',
      },
      {
        appName: 'Pipedrive',
        appCode: 'PD',
        status: 'Not Connected',
        syncState: 'Ready to connect',
        lastSync: 'No sync yet',
        description: 'Send fresh enquiries into Pipedrive and keep sales progress current.',
        primaryAction: 'Connect',
      },
      {
        appName: 'Zoho',
        appCode: 'ZO',
        status: 'Needs Attention',
        syncState: 'Reconnect recommended',
        lastSync: '2 hours ago',
        description: 'Reconnect Zoho CRM to resume lead updates and call outcome syncing.',
        primaryAction: 'Reconnect',
        secondaryAction: 'Manage',
      },
    ],
  },
  {
    title: 'Calendar Integrations',
    description: 'Sync real availability so bookings stay accurate and admin work stays low.',
    features: [
      'Sync availability',
      'Support appointment booking',
      'Reduce admin work',
      'Keep bookings aligned with the real schedule',
    ],
    items: [
      {
        appName: 'Google Calendar',
        appCode: 'GC',
        status: 'Connected',
        syncState: 'Healthy',
        lastSync: '2 minutes ago',
        description: 'Keep your live calendar availability in sync so AssistantAI can book confidently.',
        primaryAction: 'Manage',
        secondaryAction: 'Disconnect',
      },
      {
        appName: 'Outlook Calendar',
        appCode: 'OC',
        status: 'Not Connected',
        syncState: 'Ready to connect',
        lastSync: 'No sync yet',
        description: 'Connect Outlook Calendar to align bookings with Microsoft-based schedules.',
        primaryAction: 'Connect',
      },
    ],
  },
  {
    title: 'Messaging Integrations',
    description: 'Send confirmations, missed-call follow-up, and internal notifications automatically.',
    features: [
      'Send confirmations',
      'Send missed-call follow-up messages',
      'Notify staff',
      'Trigger follow-up sequences',
    ],
    items: [
      {
        appName: 'Twilio',
        appCode: 'TW',
        status: 'Connected',
        syncState: 'Healthy',
        lastSync: '7 minutes ago',
        description: 'Deliver SMS confirmations and follow-up messages immediately after each call.',
        primaryAction: 'Manage',
        secondaryAction: 'Disconnect',
      },
      {
        appName: 'GoHighLevel SMS',
        appCode: 'SMS',
        status: 'Not Connected',
        syncState: 'Ready to connect',
        lastSync: 'No sync yet',
        description: 'Use GoHighLevel SMS for reminders, staff notifications, and nurture sequences.',
        primaryAction: 'Connect',
      },
    ],
  },
  {
    title: 'Billing & Payments',
    description: 'Keep billing simple with secure payments, saved methods, and subscription management.',
    features: [
      'Manage secure payments',
      'Store billing methods',
      'Support subscription management',
      'Keep invoices in one place',
    ],
    items: [
      {
        appName: 'Stripe',
        appCode: 'ST',
        status: 'Connected',
        syncState: 'Healthy',
        lastSync: '15 minutes ago',
        description: 'Manage subscriptions, invoices, and card details in one secure billing connection.',
        primaryAction: 'Manage',
        secondaryAction: 'Disconnect',
      },
    ],
  },
  {
    title: 'Future / Optional Integrations',
    description: 'Additional tools that can extend reporting, notifications, and cross-system automation later on.',
    features: [
      'Expand automation coverage',
      'Connect team notifications',
      'Support broader workflows',
      'Prepare for future growth',
    ],
    items: [
      {
        appName: 'Zapier',
        appCode: 'ZA',
        status: 'Not Connected',
        syncState: 'Optional setup',
        lastSync: 'No sync yet',
        description: 'Link AssistantAI with thousands of business tools through flexible workflow automation.',
        primaryAction: 'Connect',
      },
      {
        appName: 'Slack',
        appCode: 'SL',
        status: 'Not Connected',
        syncState: 'Optional setup',
        lastSync: 'No sync yet',
        description: 'Send team alerts and internal updates into the right Slack channels.',
        primaryAction: 'Connect',
      },
      {
        appName: 'Microsoft Teams',
        appCode: 'MT',
        status: 'Not Connected',
        syncState: 'Optional setup',
        lastSync: 'No sync yet',
        description: 'Keep staff notified inside Teams when bookings, missed calls, or urgent jobs come in.',
        primaryAction: 'Connect',
      },
      {
        appName: 'Email Platform',
        appCode: 'EM',
        status: 'Not Connected',
        syncState: 'Optional setup',
        lastSync: 'No sync yet',
        description: 'Coordinate follow-up emails, reminders, and nurture campaigns from one connected platform.',
        primaryAction: 'Connect',
      },
    ],
  },
];